<?php
/**
 * @file
 * webform_workflow_state_field.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function webform_workflow_state_field_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-webform-field_ww_states'
  $field_instances['node-webform-field_ww_states'] = array(
    'bundle' => 'webform',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ww_states',
    'label' => 'States',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'inline_entity_form',
      'settings' => array(
        'fields' => array(),
        'type_settings' => array(),
      ),
      'type' => 'inline_entity_form',
      'weight' => -4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('States');

  return $field_instances;
}
